
package com.jaxws.sevice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "testServicePortType", targetNamespace = "http://sevice.jaxws.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestServicePortType {


    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getService")
    @WebResult(targetNamespace = "http://sevice.jaxws.com")
    @RequestWrapper(localName = "getService", targetNamespace = "http://sevice.jaxws.com", className = "com.jaxws.sevice.GetService")
    @ResponseWrapper(localName = "getServiceResponse", targetNamespace = "http://sevice.jaxws.com", className = "com.jaxws.sevice.GetServiceResponse")
    public String getService(
        @WebParam(name = "xml", targetNamespace = "http://sevice.jaxws.com")
        String xml);

}
