
package com.jaxws.sevice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "testService", targetNamespace = "http://sevice.jaxws.com", wsdlLocation = "http://localhost:8080/axis2/services/testService?wsdl")
public class TestService
    extends Service
{

    private final static URL TESTSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/axis2/services/testService?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        TESTSERVICE_WSDL_LOCATION = url;
    }

    public TestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestService() {
        super(TESTSERVICE_WSDL_LOCATION, new QName("http://sevice.jaxws.com", "testService"));
    }

    /**
     * 
     * @return
     *     returns TestServicePortType
     */
    @WebEndpoint(name = "testServiceHttpSoap11Endpoint")
    public TestServicePortType getTestServiceHttpSoap11Endpoint() {
        return (TestServicePortType)super.getPort(new QName("http://sevice.jaxws.com", "testServiceHttpSoap11Endpoint"), TestServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestServicePortType
     */
    @WebEndpoint(name = "testServiceHttpSoap11Endpoint")
    public TestServicePortType getTestServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return (TestServicePortType)super.getPort(new QName("http://sevice.jaxws.com", "testServiceHttpSoap11Endpoint"), TestServicePortType.class, features);
    }

}
